### ISSUE TITLE
Move Ping Finder Config to Attached Storage

### ISSUE THREAD

**Issue by TylerFlar** [UCSD-E4E/radio-telemetry-tracker-drone-fds#5]
## Objective
It would be nice for a user to be able to swap out the ping finder settings in offline mode in the field instead of set them in the `docker-compose.yml` file which cannot be easily accessible in the field.

## Requirements
- Config file template MUST be added to the repository.
- Config file MUST follow a conventional config file format such as INI or JSON (INI may be better for user experience)

## Tasks
1. Write a config file referencing the code below
https://github.com/UCSD-E4E/radio-telemetry-tracker-drone-fds/blob/7397b3dc3241b7784f15c727c32ce941611b06a9/radio_telemetry_tracker_drone_fds/config.py#L23-L39
2. Rewrite `config.py` to reference this file on the mounted media.

## Deliverables
- Pull request to the `dev` branch.

**Comment by ntlhui** [comment]
Note that you may have to do some `udev` magic on the host system to deterministically mount the removable volume in the right spot for the Docker bind mount.  I would recommend trying to do something like the first partition on the external drive gets mounted and bound into the container.

**Comment by TylerFlar** [comment]
I have been able to unplug and plug a USB stick back into the UP 7000 when it is turned off, and Ubuntu remounts it back to the same location. This might be sufficient for our needs since the script only re-reads the config after a reboot (i.e., the user turns off the drone/computer, removes the USB stick, edits the config, plugs the USB stick back in, turns on the drone/computer, and the docker container with the script starts). However, I'm unsure about its reliability.

**Comment by ntlhui** [comment]
It mounts to something like `/media/{uuid}`, right?  That's based on the UUID of the drive, so different drives might behave differently.  You probably also want to put in documentation what types of filesystems you are okay with (probably use exFAT).
